### ISSUE TITLE
у меня в ГХ обновление

### ISSUE THREAD

**Issue by Alexey-T** [myCrack/Ebony#3]
там новые п-ты заполнил. scrollbar**, status-alt-font.

**Comment by myCrack** [comment]
Я вижу, но не знаю как мне эти правки забирать. Т.е. я могу и здесь также сделать, но не знаю как сделать так, чтобы было видно чьи это правки...

И что делать?

**Comment by Alexey-T** [comment]
скопировать мой json. к себе.

**Comment by myCrack** [comment]
Я знаю как в TortoiseGit делать commit, pull, push. На этом мои знания GIT заканчиваются. Т.е. тебе надо самаму скопировать его сюда.

**Comment by Alexey-T** [comment]
- берешь качаешь- кликай RAW в странице ГХ
- копируешь в папку свою
- делаешь git commit, git push
- проверяешь в ГХ

**Comment by myCrack** [comment]
> не знаю как сделать так, **чтобы было видно чьи это правки**...

Вот про что я писал -- после того как я сделаю commit, не будет видно что это ты тему менял, т.е. ты сам должен делать правки.

**Comment by Alexey-T** [comment]
Да неважно. файл обновить

**Comment by myCrack** [comment]
Незачем делать fork, ты и так можеш менять этот репозиторий, прямо через веб-морду на GitHub -- https://github.com/myCrack/verbis-diablo/edit/master/verbis-diablo.json

Я вообще не создавал локального репозитория для этой темы, а все правки через web-интерфейс делал.

**Comment by Alexey-T** [comment]
Ооо, ок
