### ISSUE TITLE
up

### ISSUE THREAD

**Issue by myCrack** [myCrack/Ebony#4]
@Alexey-T 
[Изменил цвета у полосы прокрутки](https://github.com/myCrack/verbis-diablo/commit/7bda34a5fe5fc7da213dbe6e7fc82f71222608d1). Нужно обновить файл в Addon-manager.

**Comment by Alexey-T** [comment]
В Аддон нету, я обновлю в Куде после

**Comment by myCrack** [comment]
Ну, если нет в Addons, то я пожалуй переименую тему в Ebony.json, а "Verbis Diablo" оставлю на будущее (для плагина, а не темы).

**Comment by myCrack** [comment]
еще немного изменений.
