### ISSUE TITLE
Хочется тему Solarized

### ISSUE THREAD

**Issue by Alexey-T** [myCrack/Ebony#5]
тема есть для Н программ. http://ethanschoonover.com/solarized . А тут пример 

lite
https://atom.io/themes/solarized-light-ui
dark
https://atom.io/themes/atom-solarized-dark-ui
https://atom.io/themes/solarized-dark-ui

**Comment by myCrack** [comment]
Раз есть Ebony, то соответственно будет и Ivory, но это еще не скоро. И потом уже после этого если до того момента никто не сделает Solarized, то я сделаю.

**Comment by myCrack** [comment]
Эта тема уже есть в addon-manager.

**Comment by zk-t** [comment]
@myCrack test
